package com.grosner.weathertest.current.today;

import com.bluelinelabs.logansquare.annotation.JsonObject;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class Coordinate {
  public double lon;

  public double lat;
}
