package com.grosner.weathertest.current.today;

import com.bluelinelabs.logansquare.annotation.JsonObject;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class Main {
  double temp;

  double pressure;

  int humidity;

  double temp_min;

  double temp_max;

  double sea_level;

  double grnd_level;

  double temp_kf;
}
