package com.grosner.weathertest.current.today;

import com.bluelinelabs.logansquare.annotation.JsonObject;
import java.lang.String;
import java.util.List;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class WeatherForecastResponse {
  String cod;

  double message;

  int cnt;

  List<WeatherResponse> list;

  City city;
}
