package com.grosner.weathertest.current.forecast;

import com.bluelinelabs.logansquare.annotation.JsonObject;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class Coord {
  double lon;

  double lat;
}
