package com.grosner.weathertest.current.forecast;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;
import java.lang.String;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class Weather_ {
  @JsonField(
      name = "id"
  )
  int id_;

  String main;

  String description;

  String icon;
}
