package com.grosner.weathertest.current.forecast;

import com.bluelinelabs.logansquare.annotation.JsonObject;
import java.lang.String;
import java.util.List;

/**
 * This is generated by Jetty. Safe to modify as needed. */
@JsonObject(
    fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS
)
public class WeatherForecastResponse {
  City city;

  String cod;

  double message;

  int cnt;

  public List<List_> list;
}
